### PR TITLE
Revert "Fix builder menu positioning"

### PR DESCRIPTION
**Pull request by marosmars**
This reverts commit 0952e513f1ee36fba5c2ab981405651068a9beb7.

For some reason in FM this doesn't work properly

### CODE REVIEW

**Comment by ChmaraX** [comment]
Can you provide more info about what is not working? Maybe it caused another issue that got recently reported.

**Comment by marosmars** [comment]
image

**Comment by ChmaraX** [comment]
I will look at it. If it wont be a quick fix I will merge this.

**Comment by marosmars** [comment]
@ChmaraX  thanks

**Comment by ChmaraX** [comment]
The issue with css imports is causing the other bug I mentioned so you can merge this one.

**Pull request merged**
